on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build com Maven
      run: mvn -B package --file app/pom.xml
    - name: Publicando o artefato  
    - uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/results.json
        name: VeracodeBaseline
        
  Veracode_SCA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SCA }} # Lembrar de criar as credenciais no Secrets
        run: |
          curl -sSL 'https://download.sourceclear.com/ci.sh' | bash -s – scan --update-advisor --allow-dirty
        
  Veracode-SAST-Policy-Scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Archive Release
      uses: actions/setup-go@v3
      with:
        filename: 'verademo.war'
        path: ./verademo.war
                
    - uses: actions/upload-artifact@v2 
      with:
        path: ./verademo.war
    - uses: veracode/veracode-uploadandscan-action@master 
      with:
        vid: '${{ secrets.VID }}'
        vkey: '${{ secrets.VKEY }}'
        criticality: 'Medium'
        appname: 'Lab-Verademo-Java'
        createprofile: 'true'
        filepath: ./
        deleteIncompleteScan: 'true'
        version: ${{ github.run_id }}'
        scantimeout: 30

  Veracode_PipelineScan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download do Artefato
        uses: actions/download-artifact@v2
        with:
          name: artefatoveracode
      - name: Pipeline Scan     
        run: |
          curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip -o pipeline-scan-LATEST.zip
          java -jar pipeline-scan.jar -vid ${{ env.VID }} -vkey ${{ env.VKEY }} -f /home/vsts/work/1/s/app/target/verademo.war || true
